set $bg {background}
set $fg {foreground}
set $accent {color4}
set $urgent {color1}
set $inactive {color8}

# class                 border    backgr.   text   indicator   child_border
client.focused          $accent   $accent   $bg    $color4     $accent
client.focused_inactive $inactive $inactive $fg    $inactive   $inactive
client.unfocused        $inactive $bg       $fg    $inactive   $inactive
client.urgent           $urgent   $urgent   $bg    $urgent     $urgent
