set $bg      #1a1b26
set $fg      #c0caf5
set $accent  #7aa2f7
set $urgent  #f7768e
set $inactive #565f89

# class                 border    backgr.   text  indicator child_border
client.focused           $accent   $accent   $bg   $accent   $accent
client.focused_inactive  $inactive $inactive $fg   $inactive $inactive
client.unfocused         $inactive $bg       $fg   $inactive $inactive
client.urgent            $urgent   $urgent   $bg   $urgent   $urgent
