[urgency_low]
    background = "#282a36"
    foreground = "#f8f8f2"
    frame_color = "#6272a4"

[urgency_normal]
    background = "#282a36"
    foreground = "#f8f8f2"
    frame_color = "#6272a4"

[urgency_critical]
    background = "#282a36"
    foreground = "#ff5555"
    frame_color = "#ff5555"
